-- MySQL Script generated by MySQL Workbench
-- Fri Feb 10 18:29:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vueling` ;

-- -----------------------------------------------------
-- Schema vueling
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vueling` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `vueling` ;

-- -----------------------------------------------------
-- Table `vueling`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vueling`.`hotels` ;

CREATE TABLE IF NOT EXISTS `vueling`.`hotels` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `stars` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vueling`.`cities` ;

CREATE TABLE IF NOT EXISTS `vueling`.`cities` (
  `id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`flights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vueling`.`flights` ;

CREATE TABLE IF NOT EXISTS `vueling`.`flights` (
  `id` INT NOT NULL,
  `date_time` DATETIME NULL,
  `city1` INT NOT NULL,
  `city2` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flights_cities1_idx` (`city1` ASC) VISIBLE,
  INDEX `fk_flights_cities2_idx` (`city2` ASC) VISIBLE,
  CONSTRAINT `fk_flights_cities1`
    FOREIGN KEY (`city1`)
    REFERENCES `vueling`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flights_cities2`
    FOREIGN KEY (`city2`)
    REFERENCES `vueling`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`trips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vueling`.`trips` ;

CREATE TABLE IF NOT EXISTS `vueling`.`trips` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM('land', 'air') NOT NULL,
  `days` TINYINT NOT NULL,
  `hotel1` INT NULL,
  `hotel2` INT NULL,
  `flight1` INT NULL,
  `flight2` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trips_hotels1_idx` (`hotel1` ASC) VISIBLE,
  INDEX `fk_trips_hotels2_idx` (`hotel2` ASC) VISIBLE,
  INDEX `fk_trips_flights1_idx` (`flight1` ASC) VISIBLE,
  INDEX `fk_trips_flights2_idx` (`flight2` ASC) VISIBLE,
  CONSTRAINT `fk_trips_hotels1`
    FOREIGN KEY (`hotel1`)
    REFERENCES `vueling`.`hotels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_hotels2`
    FOREIGN KEY (`hotel2`)
    REFERENCES `vueling`.`hotels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_flights1`
    FOREIGN KEY (`flight1`)
    REFERENCES `vueling`.`flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_flights2`
    FOREIGN KEY (`flight2`)
    REFERENCES `vueling`.`flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vueling`.`trip_cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vueling`.`trip_cities` ;

CREATE TABLE IF NOT EXISTS `vueling`.`trip_cities` (
  `trips_id` INT NOT NULL,
  `cities_id` INT NOT NULL,
  PRIMARY KEY (`trips_id`, `cities_id`),
  INDEX `fk_trips_has_cities_cities1_idx` (`cities_id` ASC) VISIBLE,
  INDEX `fk_trips_has_cities_trips_idx` (`trips_id` ASC) VISIBLE,
  CONSTRAINT `fk_trips_has_cities_trips`
    FOREIGN KEY (`trips_id`)
    REFERENCES `vueling`.`trips` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trips_has_cities_cities1`
    FOREIGN KEY (`cities_id`)
    REFERENCES `vueling`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
